version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      # run build script
      - npm install --force
      - npm run-script build

artifacts:
  files:
    - .next/**/*
    - package.json
    - package-lock.json
    - server.js
# artifacts:
#   files:
#     - .elasticbeanstalk/**/*
#     - build/**/*
#     - public/**/*
#     - src/**/*
#     - package.json
#     - appspec.yml
#     - buildspec.yml
#     - scripts/**/*
