version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - npm install # Install project dependencies

  build:
    commands:
      - npm run build # Build the Next.js application

  post_build:
    commands:
      - zip -r application.zip . # Create a ZIP file of the built application

artifacts:
  files: application.zip
